//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeywordCrap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeywordCrap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_right_green {
            get {
                object obj = ResourceManager.GetObject("arrow_right_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back2 {
            get {
                object obj = ResourceManager.GetObject("back2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bulletIco {
            get {
                object obj = ResourceManager.GetObject("bulletIco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BuyNow {
            get {
                object obj = ResourceManager.GetObject("BuyNow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Calendar24 {
            get {
                object obj = ResourceManager.GetObject("Calendar24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Class {
            get {
                object obj = ResourceManager.GetObject("Class", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Contacts24 {
            get {
                object obj = ResourceManager.GetObject("Contacts24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;uitips&gt;
        ///
        ///&lt;uitip&gt;
        ///&lt;control&gt;txtHomePage&lt;/control&gt;
        ///&lt;text&gt;Home Page&lt;/text&gt;
        ///&lt;message&gt;The page which need to be shown by default when IE is started&lt;/message&gt;
        ///&lt;menu&gt;Behaviour &gt; Basic&lt;/menu&gt;
        ///&lt;/uitip&gt;
        ///
        ///&lt;uitip&gt;
        ///&lt;control&gt;txtNavigationSound&lt;/control&gt;
        ///&lt;text&gt;Navigation Sound&lt;/text&gt;
        ///&lt;message&gt;The sound that you hear when you click on a link&lt;/message&gt;
        ///&lt;menu&gt;Behaviour &gt; Basic&lt;/menu&gt;
        ///&lt;/uitip&gt;
        ///
        ///&lt;uitip&gt;
        ///&lt;control&gt;chkIEFullScreen&lt;/control&gt;
        ///&lt;text&gt;Startup IE in Full Screen mode&lt;/text&gt;
        ///&lt;message&gt;Open IE in full sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ControlsInfo {
            get {
                return ResourceManager.GetString("ControlsInfo", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Diary24 {
            get {
                object obj = ResourceManager.GetObject("Diary24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderList24 {
            get {
                object obj = ResourceManager.GetObject("FolderList24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mail24 {
            get {
                object obj = ResourceManager.GetObject("Mail24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Notes24 {
            get {
                object obj = ResourceManager.GetObject("Notes24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shortcut24 {
            get {
                object obj = ResourceManager.GetObject("Shortcut24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tasks24 {
            get {
                object obj = ResourceManager.GetObject("Tasks24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
